// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNEJkHlhWQKmVG1QxfhHq1-sb9C_Asx4k',
    appId: '1:656397400785:web:83a6c80fbb123129e1a3f0',
    messagingSenderId: '656397400785',
    projectId: 'my-bu-b3867',
    authDomain: 'my-bu-b3867.firebaseapp.com',
    storageBucket: 'my-bu-b3867.appspot.com',
    measurementId: 'G-KN8VZ9D7N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTulEhxrntQiIin4CztVGs1NHiG5UgCA',
    appId: '1:656397400785:android:d7e13bd8e882191fe1a3f0',
    messagingSenderId: '656397400785',
    projectId: 'my-bu-b3867',
    storageBucket: 'my-bu-b3867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdN2NahDEn7fI-R-JVs5U7rx-NvQTV-3c',
    appId: '1:656397400785:ios:88e6309da8cd19bee1a3f0',
    messagingSenderId: '656397400785',
    projectId: 'my-bu-b3867',
    storageBucket: 'my-bu-b3867.appspot.com',
    iosBundleId: 'com.example.myBu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdN2NahDEn7fI-R-JVs5U7rx-NvQTV-3c',
    appId: '1:656397400785:ios:88e6309da8cd19bee1a3f0',
    messagingSenderId: '656397400785',
    projectId: 'my-bu-b3867',
    storageBucket: 'my-bu-b3867.appspot.com',
    iosBundleId: 'com.example.myBu',
  );
}
